// Prototype of `sauf types:generate` for S2 option (c). Uses only the TS checker (no runtime import of the
// contracts): method/path are literal types, everything else is printed with typeToString.
// Writes:
//   fe/generated/manifest.ts            slim manifest (method/path/error codes), typed via `import type` (monorepo)
//   fe-separate/generated/api.ts        flattened AppApi interface + manifest, no schema/contract imports (separate repo)
// Usage: node s2-api/scripts/gen.mjs   (from spikes/v1; TS_PATH overrides the typescript location)
import { createRequire } from "node:module";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const s2 = resolve(here, "..");
const require = createRequire(import.meta.url);
const ts = require(process.env.TS_PATH ?? resolve(here, "../../../../node_modules/typescript"));

const entry = join(here, "gen-entry.ts");
const program = ts.createProgram([entry], {
  target: ts.ScriptTarget.ES2022,
  module: ts.ModuleKind.ESNext,
  moduleResolution: ts.ModuleResolutionKind.Bundler,
  strict: true,
  noEmit: true,
  skipLibCheck: true,
  types: [],
});
const diags = ts.getPreEmitDiagnostics(program);
if (diags.length) throw new Error(ts.formatDiagnostics(diags, { getCanonicalFileName: (f) => f, getCurrentDirectory: () => s2, getNewLine: () => "\n" }));

const checker = program.getTypeChecker();
const sf = program.getSourceFile(entry);
const alias = sf.statements.find((s) => ts.isTypeAliasDeclaration(s) && s.name.text === "Flat");
const flat = checker.getTypeAtLocation(alias.name);
const flags = ts.TypeFormatFlags.NoTruncation | ts.TypeFormatFlags.InTypeAlias | ts.TypeFormatFlags.UseSingleQuotesForStringLiteralType;
const str = (t) => checker.typeToString(t, alias, flags);
const prop = (t, name) => checker.getTypeOfSymbolAtLocation(t.getProperty(name), alias);

const FIELDS = ["method", "path", "params", "query", "body", "response", "status", "errors"];
// a type alias, not an interface: interfaces get no implicit index signature, so they would not satisfy ApiShape
let iface = "export type AppApi = {\n";
const manifest = {};
for (const c of flat.getProperties()) {
  const ct = checker.getTypeOfSymbolAtLocation(c, alias);
  iface += `  ${c.name}: {\n`;
  manifest[c.name] = {};
  for (const e of ct.getProperties()) {
    const et = checker.getTypeOfSymbolAtLocation(e, alias);
    iface += `    ${e.name}: {\n`;
    for (const f of FIELDS) iface += `      ${f}: ${str(prop(et, f))};\n`;
    iface += "    };\n";
    const errs = prop(et, "errors");
    const codes = (errs.isUnion() ? errs.types : errs.flags & ts.TypeFlags.Never ? [] : [errs]).map((t) => prop(t, "status").value);
    manifest[c.name][e.name] = [prop(et, "method").value, prop(et, "path").value, codes];
  }
  iface += "  };\n";
}
iface += "};\n";

const banner = "// GENERATED by s2-api/scripts/gen.mjs — do not edit.\n";
const manifestSrc = JSON.stringify(manifest, null, 2);

mkdirSync(join(s2, "fe/generated"), { recursive: true });
writeFileSync(
  join(s2, "fe/generated/manifest.ts"),
  `${banner}import type { AppApi } from "@app/contracts";\nimport type { ApiTypes } from "../../../contract";\nimport type { Manifest } from "../../client/manifest-client";\n\nexport type Api = ApiTypes<AppApi>;\nexport const manifest = ${manifestSrc} as const satisfies Manifest<Api>;\n`,
);
mkdirSync(join(s2, "fe-separate/generated"), { recursive: true });
writeFileSync(
  join(s2, "fe-separate/generated/api.ts"),
  `${banner}// Self-contained: no contract lib, no schema lib.\nimport type { Manifest } from "../../client/manifest-client";\n\n${iface}\nexport const manifest = ${manifestSrc} as const satisfies Manifest<AppApi>;\n`,
);
console.log("generated fe/generated/manifest.ts, fe-separate/generated/api.ts");
