name: 'Publish Packages'
on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish to npm registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup nodejs
        uses: ./.github/setup-node

      - name: Release
        run: pnpm build && pnpm build:type && pnpm publish -r --access public
