name: 'Publish Packages'
on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish to npm registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup bun
        uses: ./.github/setup-bun

      - name: Release
        run: bun run build && bun run build:type && bunx publish -r --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
